# Generated by Django 6.0.2 on 2026-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
