# Generated by Django 6.0.2 on 2026-02-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.theater')),
            ],
        ),
    ]
