# Generated by Django 6.0.2 on 2026-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='provider',
            field=models.CharField(default='MK2', max_length=50),
        ),
    ]
